import { useState } from 'react';
import { cn } from '@/lib/ui';
import { Avatar, NotFound, useTheme } from '@/components/shared';
import { AdminDashboard } from '@/pages/admin';
import { AdminNoteDetail } from '@/pages/admin';
import { ContributionDetail } from '@/components/ContributionDetail';
import { ContributionForm } from '@/pages/student';
import { Contributions } from '@/pages/student';
import { Dashboard } from '@/pages/student';
import { LearningPath } from '@/pages/learning-path';
import { Notifications } from '@/pages/student';
import { ProfilePage } from '@/pages/student';
import { Progress } from '@/pages/student';
import { SettingsPage } from '@/pages/student';
import { StudentDetail } from '@/pages/teacher';
import { Students } from '@/pages/teacher';
import { TeacherDashboard } from '@/pages/teacher';
import { Bell, BookOpen, CircleUserRound, Code2, LayoutDashboard, LogOut, Menu, Moon, Settings, ShieldCheck, Sun, Trophy, Users, X } from 'lucide-react';
import type { Profile } from '@/types';

export interface ShellProps { profile: Profile; route: string; navigate: (path: string) => void; signOut: () => Promise<void>; }

export function AppShell({ profile, route, navigate, signOut }: ShellProps): JSX.Element { const [mobileOpen, setMobileOpen] = useState(false); const [night, toggleTheme] = useTheme();
  const navItems = profile.role === 'admin' ? [{ path: '/admin', label: 'Admin overview', icon: ShieldCheck }, { path: '/students', label: 'Users', icon: Users }, { path: '/learning-path', label: 'Learning notes', icon: BookOpen }, { path: '/notifications', label: 'Notifications', icon: Bell }, { path: '/settings', label: 'Settings', icon: Settings }] : profile.role === 'teacher' ? [{ path: '/teacher', label: 'Overview', icon: LayoutDashboard }, { path: '/contributions', label: 'My contributions', icon: Code2 }, { path: '/students', label: 'Students', icon: Users }, { path: '/learning-path', label: 'Learning notes', icon: BookOpen }, { path: '/notifications', label: 'Notifications', icon: Bell }, { path: '/profile', label: 'Profile', icon: CircleUserRound }, { path: '/settings', label: 'Settings', icon: Settings }] : [{ path: '/dashboard', label: 'Overview', icon: LayoutDashboard }, { path: '/contributions', label: 'Contributions', icon: Code2 }, { path: '/progress', label: 'Progress', icon: Trophy }, { path: '/learning-path', label: 'Learning path', icon: BookOpen }, { path: '/students', label: 'Students', icon: Users }, { path: '/notifications', label: 'Notifications', icon: Bell }, { path: '/profile', label: 'Profile', icon: CircleUserRound }, { path: '/settings', label: 'Settings', icon: Settings }];
  const content = route === '/dashboard' || route === '/' ? <Dashboard profile={profile} navigate={navigate} /> : route === '/contributions' ? <Contributions profile={profile} navigate={navigate} /> : route === '/contributions/new' ? <ContributionForm profile={profile} navigate={navigate} /> : route.match(/^\/contributions\/[^/]+\/edit$/) ? <ContributionForm profile={profile} navigate={navigate} contributionId={route.split('/')[2]} /> : route.startsWith('/contributions/') ? <ContributionDetail profile={profile} navigate={navigate} contributionId={route.split('/')[2]} /> : route === '/progress' ? <Progress profile={profile} /> : route === '/learning-path' ? <LearningPath profile={profile} navigate={navigate} /> : route === '/students' ? <Students navigate={navigate} /> : route.startsWith('/students/') ? <StudentDetail navigate={navigate} studentId={route.split('/')[2]} /> : route.startsWith('/admin-notes/') ? <AdminNoteDetail navigate={navigate} noteId={route.split('/')[2]} profile={profile} /> : route === '/notifications' ? <Notifications profile={profile} /> : route === '/profile' ? <ProfilePage profile={profile} /> : route === '/settings' ? <SettingsPage profile={profile} /> : route === '/teacher' ? <TeacherDashboard profile={profile} navigate={navigate} /> : route === '/admin' ? <AdminDashboard profile={profile} navigate={navigate} /> : <NotFound navigate={navigate} />;
  return <div className="app-shell">{mobileOpen && <div className="fixed inset-0 z-20 bg-[#061c2c]/40 lg:hidden" onClick={() => setMobileOpen(false)} />}<button className="fixed right-5 top-5 z-40 rounded-xl bg-[#061c2c] p-3 text-white shadow-lg lg:hidden" onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? <X /> : <Menu />}</button><button title={night ? 'Switch to day theme' : 'Switch to night theme'} onClick={toggleTheme} className="fixed right-20 top-5 z-40 rounded-xl border border-[#dce9e6] bg-white p-3 text-[#087f78] shadow-lg transition hover:bg-[#f0faf7]">{night ? <Sun className="h-5 w-5" /> : <Moon className="h-5 w-5" />}</button><aside className={cn('fixed inset-y-0 left-0 z-30 flex w-72 flex-col border-r border-[#dce9e6] bg-white px-5 py-6 transition-transform lg:translate-x-0', mobileOpen ? 'translate-x-0' : '-translate-x-full')}><div className="flex items-center gap-3 px-3"><div className="rounded-xl bg-[#087f78] p-2 text-white"><Code2 className="h-5 w-5" /></div><span className="font-bold tracking-tight text-[#102a3a]">Fullstack<span className="text-[#087f78]">Dev</span></span></div><div className="mt-10 flex items-center gap-3 rounded-2xl bg-[#f0f8f5] p-3"><Avatar profile={profile} /><div className="min-w-0"><p className="truncate text-sm font-bold text-[#102a3a]">{profile.full_name || 'Developer'}</p><p className="text-xs capitalize text-[#6c8589]">{profile.role}</p></div></div><nav className="mt-8 flex-1 space-y-1">{navItems.map((item) => { const Icon = item.icon; return <button key={item.path} onClick={() => { navigate(item.path); setMobileOpen(false); }} className={cn('flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold transition', route === item.path || (item.path === '/contributions' && route.startsWith('/contributions')) ? 'bg-[#e7f7f1] text-[#087f78]' : 'text-[#6c8589] hover:bg-[#f2f8f6] hover:text-[#185464]')}><Icon className="h-[18px] w-[18px]" />{item.label}</button>; })}</nav><button onClick={() => void signOut()} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-[#6c8589] transition hover:bg-[#fff4f4] hover:text-[#a33b3b]"><LogOut className="h-[18px] w-[18px]" />Sign out</button></aside><main className="min-h-screen lg:pl-72"><div className="mx-auto max-w-[1440px] px-5 py-8 sm:px-8 lg:px-12 lg:py-10">{content}</div></main></div>;
}
